name: Update build.yaml on new submodule release

on:
  push:
    branches:
      - dependabot/submodules/** # Déclenché par Dependabot lors d'une mise à jour d'un sous-module
  workflow_dispatch: # Permet de lancer manuellement l’action si nécessaire

permissions:
  contents: write
  pull-requests: write

jobs:
  update-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: true # Clone aussi les sous-modules

      - name: Get latest versions of submodules
        run: |
          # SEAT
          LATEST_SEAT_VERSION=$(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-connector-seatcupra.git | awk '{print $2}' | grep -Eo 'v[0-9]+.[0-9]+.[0-9]+' | sort -V | tail -n 1 | sed 's/^v//')
          echo "LATEST_SEAT_VERSION=$LATEST_SEAT_VERSION" >> $GITHUB_ENV
          
          # SKODA
          LATEST_SKODA_VERSION=$(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-connector-skoda.git | awk '{print $2}' | grep -Eo 'v[0-9]+.[0-9]+.[0-9]+' | sort -V | tail -n 1 | sed 's/^v//')
          echo "LATEST_SKODA_VERSION=$LATEST_SKODA_VERSION" >> $GITHUB_ENV

          # VOLKSWAGEN
          LATEST_VW_VERSION=$(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-connector-volkswagen.git | awk '{print $2}' | grep -Eo 'v[0-9]+.[0-9]+.[0-9]+' | sort -V | tail -n 1 | sed 's/^v//')
          echo "LATEST_VW_VERSION=$LATEST_VW_VERSION" >> $GITHUB_ENV

          # TRONITY
          LATEST_TRONITY_VERSION=$(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-connector-tronity.git | awk '{print $2}' | grep -Eo 'v[0-9]+.[0-9]+.[0-9]+' | sort -V | tail -n 1 | sed 's/^v//')
          echo "LATEST_TRONITY_VERSION=$LATEST_TRONITY_VERSION" >> $GITHUB_ENV

          # MQTT
          LATEST_MQTT_VERSION=$(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-plugin-mqtt.git | awk '{print $2}' | grep -Eo 'v[0-9]+.[0-9]+.[0-9]+' | sort -V | tail -n 1 | sed 's/^v//')
          echo "LATEST_MQTT_VERSION=$LATEST_MQTT_VERSION" >> $GITHUB_ENV

          # MQTT Home Assistant
          LATEST_MQTT_HOMEASSISTANT_VERSION=$(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-plugin-mqtt_homeassistant.git | awk '{print $2}' | grep -Eo 'v[0-9]+.[0-9]+.[0-9]+' | sort -V | tail -n 1 | sed 's/^v//')
          echo "LATEST_MQTT_HOMEASSISTANT_VERSION=$LATEST_MQTT_HOMEASSISTANT_VERSION" >> $GITHUB_ENV

          # WebUI Home Assistant
          LATEST_WEBUI_VERSION=$(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-plugin-webui.git | awk '{print $2}' | grep -Eo 'v[0-9]+.[0-9]+.[0-9]+' | sort -V | tail -n 1 | sed 's/^v//')
          echo "LATEST_WEBUI_VERSION=$LATEST_WEBUI_VERSION" >> $GITHUB_ENV
          
          # Carconnectivity
          LATEST_CC_VERSION=$(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity.git | awk '{print $2}' | grep -Eo 'v[0-9]+.[0-9]+.[0-9]+' | sort -V | tail -n 1 | sed 's/^v//')
          echo "LATEST_CC_VERSION=$LATEST_CC_VERSION" >> $GITHUB_ENV
          
      - name: Generate changelog
        run: |
          echo "### Changelog der Aktualisierungen" > CHANGELOG.md
          
          echo "- **Carconnectivity_VERSION** → \`${LATEST_CC_VERSION}\`" >> CHANGELOG.md
          echo "- **SEAT_VERSION** → \`${LATEST_SEAT_VERSION}\`" >> CHANGELOG.md
          echo "- **SKODA_VERSION** → \`${LATEST_SKODA_VERSION}\`" >> CHANGELOG.md
          echo "- **VOLKSWAGEN_VERSION** → \`${LATEST_VW_VERSION}\`" >> CHANGELOG.md
          echo "- **TRONITY_VERSION** → \`${LATEST_TRONITY_VERSION}\`" >> CHANGELOG.md
          echo "- **MQTT_VERSION** → \`${LATEST_MQTT_VERSION}\`" >> CHANGELOG.md
          echo "- **MQTT_HOMEASSISTANT_VERSION** → \`${LATEST_MQTT_HOMEASSISTANT_VERSION}\`" >> CHANGELOG.md

          echo "- **WEBUI_VERSION** → \`${LATEST_WEBUI_VERSION}\`" >> CHANGELOG.md
          echo "" >> CHANGELOG.md


          echo "#### 📌 Änderungen seit der letzten Version :" >> CHANGELOG.md


          # Generierung von Logs für jedes Untermodul
          echo "**SeatCupra** :" >> CHANGELOG.md
          git log --pretty=format:"- %h %s" $(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-connector-seatcupra.git | awk '{print $1}' | tail -n 2 | head -n 1)..HEAD >> CHANGELOG.md || echo "Pas de nouvelles modifications" >> CHANGELOG.md

          echo "**Skoda** :" >> CHANGELOG.md
          git log --pretty=format:"- %h %s" $(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-connector-skoda.git | awk '{print $1}' | tail -n 2 | head -n 1)..HEAD >> CHANGELOG.md || echo "Pas de nouvelles modifications" >> CHANGELOG.md

          echo "**Volkswagen** :" >> CHANGELOG.md
          git log --pretty=format:"- %h %s" $(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-connector-volkswagen.git | awk '{print $1}' | tail -n 2 | head -n 1)..HEAD >> CHANGELOG.md || echo "Pas de nouvelles modifications" >> CHANGELOG.md

          echo "**Tronity** :" >> CHANGELOG.md
          git log --pretty=format:"- %h %s" $(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-connector-tronity.git | awk '{print $1}' | tail -n 2 | head -n 1)..HEAD >> CHANGELOG.md || echo "Pas de nouvelles modifications" >> CHANGELOG.md

          echo "**MQTT** :" >> CHANGELOG.md
          git log --pretty=format:"- %h %s" $(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-plugin-mqtt.git | awk '{print $1}' | tail -n 2 | head -n 1)..HEAD >> CHANGELOG.md || echo "Pas de nouvelles modifications" >> CHANGELOG.md

          echo "**MQTT HomeAssistant** :" >> CHANGELOG.md
          git log --pretty=format:"- %h %s" $(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-plugin-mqtt_homeassistant.git | awk '{print $1}' | tail -n 2 | head -n 1)..HEAD >> CHANGELOG.md || echo "Pas de nouvelles modifications" >> CHANGELOG.md

          echo "**WEBUI_VERSION** :" >> CHANGELOG.md
          git log --pretty=format:"- %h %s" $(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity-plugin-webui.git | awk '{print $1}' | tail -n 2 | head -n 1)..HEAD >> CHANGELOG.md || echo "Pas de nouvelles modifications" >> CHANGELOG.md

          echo "**Carconnectivity_VERSION** :" >> CHANGELOG.md
          git log --pretty=format:"- %h %s" $(git ls-remote --tags https://github.com/tillsteinbach/CarConnectivity.git | awk '{print $1}' | tail -n 2 | head -n 1)..HEAD >> CHANGELOG.md || echo "Pas de nouvelles modifications" >> CHANGELOG.md


      - name: Update build.yaml
        run: |

          echo "Aktualisieren von build.yaml mit neuen Versionen"
          sed -i "s/SEAT_VERSION: .*/SEAT_VERSION: \"${LATEST_SEAT_VERSION}\"/" build.yaml
          sed -i "s/SKODA_VERSION: .*/SKODA_VERSION: \"${LATEST_SKODA_VERSION}\"/" build.yaml
          sed -i "s/VW_VERSION: .*/VW_VERSION: \"${LATEST_VW_VERSION}\"/" build.yaml
          sed -i "s/TRONITY_VERSION: .*/TRONITY_VERSION: \"${LATEST_TRONITY_VERSION}\"/" build.yaml
          sed -i "s/MQTT_VERSION: .*/MQTT_VERSION: \"${LATEST_MQTT_VERSION}\"/" build.yaml
          sed -i "s/MQTT_HOMEASSISTANT_VERSION: .*/MQTT_HOMEASSISTANT_VERSION: \"${LATEST_MQTT_HOMEASSISTANT_VERSION}\"/" build.yaml
          sed -i "s/WEBUI_VERSION: .*/WEBUI_VERSION: \"${LATEST_WEBUI_VERSION}\"/" build.yaml
          sed -i "s/CC_VERSION: .*/CC_VERSION: \"${LATEST_CC_VERSION}\"/" build.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Aktualisieren von Versionen: CC, SEAT, SKODA, VOLKSWAGEN, TRONITY, MQTT, MQTT_HOMEASSISTANT"
          git push origin HEAD:update-versions-${LATEST_SEAT_VERSION}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-versions-${LATEST_SEAT_VERSION}

          title: "Aktualisieren von Versionen"
          body: |

            Automatisch generiert von GitHub Actions.

            - **Carconnectivity_VERSION** → `${LATEST_CC_VERSION}`
            - **SEAT_VERSION** → `${LATEST_SEAT_VERSION}`
            - **SKODA_VERSION** → `${LATEST_SKODA_VERSION}`
            - **VW_VERSION** → `${LATEST_VW_VERSION}`
            - **TRONITY_VERSION** → `${LATEST_TRONITY_VERSION}`
            - **MQTT_VERSION** → `${LATEST_MQTT_VERSION}`
            - **MQTT_HOMEASSISTANT_VERSION** → `${LATEST_MQTT_HOMEASSISTANT_VERSION}`
            - **WEBUI_VERSION** → `${LATEST_WEBUI_VERSION}`

            ---
            ## Changelog 📜

            $(cat CHANGELOG.md)
          base: main
